version: "2"

services:
    postgres-db:
        image: postgres
        ports:
            - "5444:5432"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=test_db_pass
            - POSTGRES_DB=test
            - PGDATA=/var/lib/postgresql/pgdata:/var/lib/postgresql/data
        volumes:
            - /var/lib/postgresql/pgdata:/var/lib/postgresql/
