version: "2"

services:
    postgres-db:
        restart: always
        image: postgres:9.5
        ports:
            - "5489:5432"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=pass123321
            - POSTGRES_DB=shop
            - PGDATA=/var/lib/postgresql/pgdata_api:/var/lib/postgresql/data
        volumes:
            - /var/lib/postgresql/pgdata_api:/var/lib/postgresql/
